### PR TITLE
System led blinks when settings is OK

### PR DESCRIPTION
**Pull request by maditnerd**
Useful if you don't have a way to check if your settings was properly configured

It will make the system led (the green one which is used to display SD card usage) blinks if the program was loaded successfully.

### CODE REVIEW

**Comment by josephernest** [comment]
Merged! Thanks again, I can't imagine it's been 7 years!

**Comment by josephernest** [comment]
It seems that it doesn't work anymore (I tested on a RPi2 with RaspiOS Lite):

```
Using username "pi".
Linux raspberrypi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l

pi@raspberrypi:~ $ sudo echo heartbeat >/sys/class/leds/led0/trigger
-bash: /sys/class/leds/led0/trigger: Permission denied
```

I'll temporarily remove this PR in a next commit.

**Comment by josephernest** [comment]
Now included in the latest release https://github.com/josephernest/SamplerBox/releases/tag/2022-08-10-release (ready-to-use ISO image), it's quite useful, thanks for this idea @maditnerd!

**Comment by maditnerd** [comment]
You're welcome, nice to see a new release 👍

**Pull request merged**
